blank_issues_enabled: true
contact_links:
  - name: Link 1
    url: http://example.com
    about: example 1
  - name: Link 2
    url: http://example.net
    about: example 2
  - name: link 3
    url: https://example.org
    about: example 3
